### get all blogs
GET http://localhost:3003/api/blogs

### create a blog
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "vs rest",
    "author": "author name",
    "url": "url",
    "likes": 1
}

### get all users
GET http://localhost:3003/api/blogs

### create a user
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "abc",
    "password": "1234",
    "name": "username"
}
